load_data:
  storage_type: hdfs
  storage_params:
    hdfs_host: namenode
    hdfs_port: 9000
    data_path: 
      - /data/102109_tfMRI_EMOTION_LR.nii.gz
      - /data/102614_tfMRI_EMOTION_LR.nii.gz
    data_format: nifti
  database_type: hive
  database_params:
    database_host: hive-server
    database_port: 10000
    database_name: neuro
    table_name: metadata

preprocessing:
  method: smoothing
  params:
    sigma: 1.0
    
decomposition:
  method: pca
  decomposition_params:
    n_components: 10

training_strategy_configuration:
  training_model: svm
  model_type: classification #classification or regression
  label_name: sex
  evaluator: BinaryClassificationEvaluator
  model_params:
    kernel: linear
    C: 1.0
    evaluator: BinaryClassificationEvaluator
  train_test_val_split_params:
    val_size: 0.2
    test_size: 0.2
    random_state: 42
    shuffle: True
    stratify: None
  grid_search_params:
    type: random
    n_iter: 10